/* ROTEIRO COMERCIAL — ICBARI (SDR + Closer + Jornada do Paciente)
   Identidade NEUTRA (a atualizar quando chegar a marca). Conteúdo compartilhado
   entre o sistema (Roteiro) e as apresentações comerciais. */
window.ICBARI_INFO={
  nome:"ICBARI",
  sub:"Instituto de Cirurgia Bariátrica, Digestiva e Especialidades",
  frase:"Transformamos vidas além da balança: cirurgia com acompanhamento multidisciplinar do primeiro contato ao pós-operatório.",
  pilares:[
   {t:"Consulta que orienta",d:"Avaliação com o cirurgião, indicação do procedimento e plano claro. A gente explica como amigo, sem jargão."},
   {t:"Jornada conduzida",d:"A clínica marca todos os exames e a cirurgia, e o paciente é acompanhado por nutricionista, psicóloga e endocrinologista."},
   {t:"Cuidado que continua",d:"Acompanhamento no pós com nutri por 6 meses e suporte psicológico. Aqui ninguém opera e abandona."}
  ]
};
window.ROTEIRO_ICBARI={
 "sdr":[
  {n:1,title:"ICBARI",t:"Pré-ligação · 30s",tec:"Preparação · mindset",
   s:"**Antes de discar (10s):** respire, sorria, tom firme e acolhedor. Você não está vendendo — está **cuidando de uma pessoa** que procurou ajuda para um problema de saúde.\nTenha à mão: nome, por qual canal a pessoa chegou e a queixa/procedimento de interesse, se houver.\n\n**ESPELHAMENTO (regra de ouro):** copie o ritmo da pessoa — fala rápido, fale rápido; fala devagar, vá devagar. Quanto mais parecido, mais confiança.",
   do:"Sorria (ouve-se no telefone). Tom sereno passa segurança em tema de saúde.",
   av:"Ligar no automático, robotizado, ou tratar como venda comum."},
  {n:2,title:"Primeiro a pessoa. Depois o procedimento.",t:"Abertura · 1 a 3 min",tec:"Rapport · acolhimento",
   s:"**Abertura (nunca \"2 minutinhos\"):**\n\"Olá {NOME}, tudo bem? Aqui é {SDR}, da ICBARI. Vi que você buscou informação sobre {PROCEDIMENTO}. Posso te fazer umas perguntas rápidas pra entender seu caso e te orientar do jeito certo?\"\n\n**Acolhimento:** \"Há quanto tempo você convive com isso?\" → ouça. \"Já procurou algum médico antes?\" → ouça.\n→ Valide o sentimento: \"Entendo, é desconfortável mesmo. Você fez certo em buscar avaliação.\"",
   do:"Fale o nome 2–3x. Uma pergunta de cada vez. Ouça de verdade.",
   av:"Emendar perguntas sem ouvir. Ir direto ao preço ou à agenda."},
  {n:3,title:"Só quero te entender.",t:"Intenções · 40s",tec:"Baixa a guarda",
   s:"**Setar as intenções:**\n\"{NOME}, deixa eu deixar claro: **um** — eu não vou te empurrar nada; **dois** — quero primeiro entender o seu caso pra ver o melhor caminho; **três** — e te explicar como funciona a nossa clínica, pra você decidir com clareza. Combinado?\" → **espere o \"combinado\".**",
   do:"Diga \"combinado?\" e faça silêncio até o sim.",
   av:"Emendar sem pausa — a pausa gera a concordância."},
  {n:4,title:"O que muda com a ICBARI.",t:"Pitch curto · 1 a 2 min",tec:"Vender a jornada",
   s:"**Pitch curto — venda a CONDUÇÃO (é o coração):**\n\"{NOME}, o que faz a ICBARI diferente é que a gente **conduz a sua jornada inteira**. Muita gente adia cirurgia porque se perde no meio de exames, autorizações e agendamentos. Aqui não: depois que o cirurgião avalia e indica o procedimento, **a nossa equipe marca todos os exames, as avaliações e a própria cirurgia** — e ainda te acompanha no pós-operatório. Você cuida da sua saúde, a gente cuida da logística.\"\n\n**Micropacto:** \"Faz sentido ter esse acompanhamento?\"",
   do:"Enfatize: a clínica marca tudo. Isso tira o medo do processo.",
   av:"Despejar lista de cirurgias. Aqui o foco é a CONDUÇÃO."},
  {n:5,title:"Vídeo e robótica.",t:"Segurança · 1 min",tec:"Autoridade técnica",
   s:"**Gerar segurança (sem tecniquês):**\n\"E as cirurgias são feitas por **videolaparoscopia e por técnica robótica** — que costumam ter **menos dor, recuperação mais rápida e cicatrizes menores** que a cirurgia aberta. É o que há de mais moderno para o aparelho digestivo.\"\n\nSe couber, cite **1 caso curto** de paciente que se recuperou bem.",
   do:"Traduza o benefício: menos dor, volta mais rápido à rotina.",
   av:"Prometer resultado ou falar termo técnico sem explicar."},
  {n:6,title:"As perguntas que qualificam.",t:"Qualificação · o coração do SDR",tec:"Situação + dor + urgência",
   s:"**Qualificação (anote tudo):**\n1) \"{NOME}, me conta com suas palavras: **o que você está sentindo** / qual o problema?\" → anote.\n2) \"Há **quanto tempo**? Está atrapalhando o seu dia a dia?\" → anote a urgência.\n3) \"Você já tem **algum exame ou laudo** recente? Já passou por outro médico?\" → anote.\n4) \"Você tem **convênio** ou pensa em particular?\" → anote (sem prometer cobertura).\n\n→ **Não diagnostique.** Você mapeia o caso para o cirurgião.",
   do:"Anote queixa, tempo, exames prévios e convênio — o closer/médico usa tudo.",
   av:"Dar diagnóstico ou opinião clínica. Isso é do médico."},
  {n:7,title:"O próximo passo é a consulta.",t:"Transição · 1 a 2 min",tec:"Agendar a avaliação",
   s:"**Conduzir para a consulta:**\n\"{NOME}, pelo que você me contou, o passo certo agora é uma **consulta de avaliação com o nosso cirurgião**. É nela que ele examina, esclarece suas dúvidas e, se for o caso, indica o procedimento e explica a jornada.\"\n\nFeche com **duas opções**: \"Tenho **quinta 10h ou sexta 16h** — qual encaixa melhor?\"\n\n**Se pedir preço da cirurgia:** \"O valor a gente fecha na consulta, porque depende da avaliação do médico — antes disso qualquer número seria chute, e eu não quero te enganar.\"",
   do:"Ofereça 2 horários fechados. Confirme dados de contato e e-mail.",
   av:"\"Me avisa quando puder\". Dar preço de cirurgia por telefone."},
  {n:8,title:"Objeção é pedido de clareza.",t:"Objeções · sob demanda",tec:"Devolve → reenquadra → agenda",
   s:"**Objeções — só para vender a consulta:**\n\"Está caro\" → \"A consulta é o primeiro passo e é onde tudo fica claro; sem ela nem dá pra falar de valores.\"\n\"Tenho medo de cirurgia\" → \"É super normal. A consulta serve justamente pra tirar esse medo com informação — e nossas técnicas são minimamente invasivas.\"\n\"Vou pensar\" → \"Claro. Só pra eu te ajudar: o que mais pesa na sua decisão? Enquanto isso, deixo um horário reservado.\"\n\"Preciso ver com a família\" → \"Ótimo, traga quem você quiser na consulta.\"",
   do:"Trate a objeção e volte para o agendamento. Acolha o medo.",
   av:"Discutir. Prometer cobertura de convênio. Insistir sem empatia."},
  {n:9,title:"Confirmado e sem sumiço.",t:"Fechamento do agendamento",tec:"E-mail + confirmação + lembrete",
   s:"**Fechar o agendamento:**\n\"Fechado, {NOME}: **{DIA} às {HORA}**. Vou te mandar a confirmação — **me passa seu melhor e-mail e WhatsApp**. Você vai receber lembrete um dia antes e no dia. Se precisar remarcar, é só me chamar.\"\n\nPasse o contexto quente (queixa, tempo, exames prévios, convênio) para o Closer/médico. **Nada se perde no sistema.**",
   do:"Capture e-mail/WhatsApp, confirme e ative o lembrete anti-falta.",
   av:"Encerrar sem contato e sem próximo passo."}
 ],
 "closer":[
  {n:1,title:"Conduzir uma decisão de saúde.",t:"Pré-consulta · mindset",tec:"Sereno · preparado",
   s:"Antes da consulta: **tom sereno**, ritmo calmo. Em saúde, o silêncio e a segurança valem mais que a pressa. Releia as anotações do SDR: **queixa, tempo, exames prévios, convênio, medo**.\n\n**ESPELHAMENTO:** acompanhe o ritmo do paciente.",
   do:"Chegue sabendo o caso. Confirme o nome e como a pessoa prefere ser chamada.",
   av:"Recomeçar do zero, ignorando o que o SDR já mapeou."},
  {n:2,title:"Retomar antes de indicar.",t:"Abertura · 2 a 4 min",tec:"Rapport + recap",
   s:"**Retomada:**\n\"{NOME}, o {SDR} me passou seu caso. Deixa eu confirmar rapidinho pra não te fazer repetir tudo: você sente **{DOR}** há **{TEMPO}**, já fez **{EXAMES}** e tem **{CONVÊNIO}**. É isso?\" → confirme cada ponto.\n\nRecrie o pacto: **não vim te empurrar cirurgia, vim entender e te orientar.**",
   do:"Confirme os pontos em voz alta. Mostre que a clínica já conhece o caso.",
   av:"Ir direto ao procedimento sem reconfirmar a dor e o histórico."},
  {n:3,title:"A avaliação (o médico conduz).",t:"Consulta · exame",tec:"Escuta + exame",
   s:"**Momento clínico (do cirurgião):**\nEscuta ativa, exame físico, leitura dos exames trazidos. O papel comercial aqui é **preparar o terreno**: garantir que o paciente se sinta ouvido e seguro, e organizar a papelada para o médico.\n\nAo fim, o médico dá a **indicação**: qual procedimento, por qual técnica (vídeo/robótica) e por quê.",
   do:"Deixe o paciente falar. Anote dúvidas para responder depois.",
   av:"Atropelar a fala do médico ou do paciente com assunto comercial."},
  {n:4,title:"O plano cirúrgico, em palavras simples.",t:"Apresentação · 3 a 5 min",tec:"Traduzir a conduta",
   s:"**Explicar a conduta (sem tecniquês):**\n\"{NOME}, o que o doutor indicou é o **{PROCEDIMENTO}**, feito por {TÉCNICA}. Na prática significa: {BENEFÍCIO — ex.: resolver o refluxo, corrigir a hérnia, tratar a obesidade}.\"\n\nMostre a **jornada**: \"O caminho é este — a gente marca os seus **exames pré-operatórios** e as **avaliações** (cardiologista, anestesista e o que o seu caso pedir), depois o **retorno ao médico** com os resultados, aí **marcamos a cirurgia** no hospital e cuidamos do **pós-operatório**.\"\n\n**Micropacto:** \"Ficou claro o caminho?\"",
   do:"Use a Jornada do Paciente na tela. Uma etapa de cada vez.",
   av:"Enterrar o paciente em termos médicos. Pular a explicação da jornada."},
  {n:5,title:"Imagine já resolvido.",t:"Benefício · 1 min",tec:"Benefício do benefício",
   s:"**Projetar o depois:**\n\"{NOME}, imagina daqui a alguns meses: **sem {DOR}**, voltando a {ATIVIDADE que ele citou}, com a saúde em dia. É isso que a cirurgia devolve pra você — não é sobre o procedimento, é sobre a **vida depois dele**.\"\n\n→ deixe o paciente completar o cenário.",
   do:"Pinte o futuro com as palavras que ELE usou. Depois cale-se.",
   av:"Voltar ao racional cedo demais."},
  {n:6,title:"Segurança e quem cuida de você.",t:"Confiança · 1 a 2 min",tec:"Equipe + condução",
   s:"**Reforçar segurança:**\n\"Você não vai ficar perdido em nada. Tem uma **equipe da clínica** que marca cada exame, te manda os horários no WhatsApp e no seu e-mail, e acompanha tudo. E a técnica é **minimamente invasiva** — menos dor e recuperação mais rápida.\"\n\n**Antecipar dúvidas:** \"Você deve estar se perguntando: e os exames? e a autorização do convênio? e a recuperação? A gente cuida de cada um desses pontos com você.\"",
   do:"Mostre que a clínica conduz. Isso é o principal diferencial.",
   av:"Deixar a sensação de que o paciente vai ter que se virar sozinho."},
  {n:7,title:"O investimento, com transparência.",t:"Valores · 3 a 5 min",tec:"Ancorar valor → preço",
   s:"**Antes do preço, o valor:**\n\"Nesse acompanhamento está tudo: a **condução da jornada**, a marcação dos exames e da cirurgia, a **técnica moderna** e o **pós-operatório**. É um cuidado completo, não só o ato cirúrgico.\"\n\nApresente o **valor** com firmeza e **faça silêncio**. Se houver convênio: explique o que a clínica ajuda a solicitar, **sem prometer cobertura** (\"quem autoriza é o convênio; a gente prepara toda a documentação certinha\").\n\n**Isolar o preço:** \"Se o investimento couber no seu planejamento, é isso que você quer resolver, certo?\"",
   do:"Ancore o cuidado completo. Diga o valor e cale-se. Seja transparente sobre convênio.",
   av:"Prometer cobertura. Falar por cima do silêncio. Dar desconto cedo."},
  {n:8,title:"Argumenta › Acolhe › Encaminha.",t:"Fechamento · objeções",tec:"Empatia + próximo passo",
   s:"**Fechamento com empatia:**\n**\"Vou pensar\":** \"Faz todo sentido. Me diz: sua dúvida é sobre o **procedimento**, sobre o **valor** ou sobre o **momento**? Assim eu te ajudo a decidir com clareza.\"\n**\"Medo da cirurgia\":** \"É natural. Por isso a gente conduz passo a passo e usa técnica minimamente invasiva. O que mais te assusta? Vamos falar sobre isso.\"\n**\"Preciso ver o convênio\":** \"Perfeito — já deixo a documentação pronta pra solicitar a autorização. Enquanto isso, começamos os exames?\"\n\n**Encaminhar:** \"O primeiro passo concreto é **começar os exames**. Posso já iniciar sua jornada no sistema e a nossa equipe marca o primeiro exame ainda essa semana?\"",
   do:"Acolha a emoção, isole a real objeção e encaminhe para o próximo passo concreto.",
   av:"Pressionar em tema de saúde. Discutir. Ignorar o medo."},
  {n:9,title:"Bem-vindo à jornada.",t:"Pós-fechamento",tec:"Iniciar a jornada + handoff CS",
   s:"**Iniciar de verdade:**\n\"{NOME}, então vamos começar! Vou **abrir sua jornada** aqui no sistema e a nossa equipe de acompanhamento já entra em contato pra marcar seus exames. Você vai receber tudo no WhatsApp e no e-mail.\"\n\nCrie a **Jornada do Paciente** (escolhendo o procedimento — os exames entram automaticamente) e passe o caso para o **CS/pós-venda**. Comemore a decisão com o paciente.",
   do:"Abra a Jornada na hora e faça o handoff para o CS. Mande o 1º passo no WhatsApp.",
   av:"Encerrar sem iniciar a jornada. Deixar o pós no vácuo."}
 ],
 "jornada":[
  {n:1,title:"Boas-vindas",t:"CS · Dia 0",tec:"Acolher + alinhar",
   s:"Dê as **boas-vindas**, confirme dados e e-mail e explique: **a clínica vai marcar todos os exames e a cirurgia**. Envie a **lista de exames** do procedimento (ela já aparece na jornada).",
   do:"Confirme WhatsApp e e-mail. Envie a lista de exames.",
   av:"Sumir depois do fechamento."},
  {n:2,title:"Marcação dos exames",t:"CS · Exames",tec:"Agendar + avisar",
   s:"Para cada exame/avaliação: **agende** (médico/local, telefone, data), gere o **evento no calendário** do paciente e envie por **WhatsApp e e-mail**. Registre a **data prevista do resultado**.",
   do:"Um item de cada vez. Sempre envie calendário + WhatsApp + e-mail.",
   av:"Marcar sem avisar o paciente."},
  {n:3,title:"Resultados e retorno",t:"CS · Resultados → Retorno",tec:"Coletar + retornar",
   s:"Acompanhe os **resultados** (ligue para confirmar as datas). Com tudo em mãos, **marque o retorno ao cirurgião** para a decisão da cirurgia.",
   do:"Só marque o retorno com todos os resultados prontos.",
   av:"Marcar retorno faltando exame."},
  {n:4,title:"Marcar a cirurgia",t:"CS · Hospital",tec:"Checklist do hospital",
   s:"Marque a cirurgia no hospital e confira o **checklist**: pedido médico com código, laudos dos exames, termos de consentimento (cirúrgico e anestésico), autorização do convênio/OPME quando houver e documentos do paciente.",
   do:"Use o checklist da jornada. Confirme autorização antes da data.",
   av:"Marcar a data sem a autorização/documentos."},
  {n:5,title:"Pós-operatório",t:"CS · 1, 2 e 3 meses",tec:"Cuidar que continua",
   s:"Faça o acompanhamento em **1, 2 e 3 meses**, **independentemente** de o paciente ter retornado. Pergunte como está, registre a observação e ofereça ajuda. É aqui que nasce a **indicação**.",
   do:"Contate nos 3 marcos. Registre tudo (nada se perde).",
   av:"Só acompanhar quem reclama."}
 ]
};
