/* ROTEIRO COMERCIAL — ICBARI (SDR + Closer + Jornada do Paciente)
   Identidade NEUTRA (a atualizar quando chegar a marca). Conteúdo compartilhado
   entre o sistema (Roteiro) e as apresentações comerciais. */
window.ICBARI_INFO={
  nome:"ICBARI",
  sub:"Instituto de Cirurgia Bariátrica, Digestiva e Especialidades",
  frase:"Transformamos vidas além da balança: cirurgia com acompanhamento multidisciplinar do primeiro contato ao pós-operatório.",
  pilares:[
   {t:"Consulta que orienta",d:"Avaliação com o cirurgião, indicação do procedimento e plano claro. A gente explica como amigo, sem jargão."},
   {t:"Jornada conduzida",d:"A clínica marca todos os exames e a cirurgia, e o paciente é acompanhado por nutricionista, psicóloga e endocrinologista."},
   {t:"Cuidado que continua",d:"Acompanhamento no pós com nutri por 6 meses e suporte psicológico. Aqui ninguém opera e abandona."}
  ]
};
window.ROTEIRO_ICBARI={
 "sdr":[
  {n:1,title:"ICBARI",t:"Pré-ligação · 30s",tec:"Preparação · mindset",
   s:"**Antes de discar (10s):** respire, sorria, tom firme e acolhedor. Você não está vendendo — está **cuidando de uma pessoa** que procurou ajuda para um problema de saúde.\nTenha à mão: nome, por qual canal a pessoa chegou e a queixa/procedimento de interesse, se houver.\n\n**ESPELHAMENTO (regra de ouro):** copie o ritmo da pessoa — fala rápido, fale rápido; fala devagar, vá devagar. Quanto mais parecido, mais confiança.",
   do:"Sorria (ouve-se no telefone). Tom sereno passa segurança em tema de saúde.",
   av:"Ligar no automático, robotizado, ou tratar como venda comum."},
  {n:2,title:"Primeiro a pessoa. Depois o procedimento.",t:"Abertura · 1 a 3 min",tec:"Rapport · acolhimento",
   s:"**Abertura (nunca \"2 minutinhos\"):**\n\"Olá {NOME}, tudo bem? Aqui é {SDR}, da ICBARI. Vi que você buscou informação sobre {PROCEDIMENTO}. Posso te fazer umas perguntas rápidas pra entender seu caso e te orientar do jeito certo?\"\n\n**Acolhimento:** \"Há quanto tempo você convive com isso?\" → ouça. \"Já procurou algum médico antes?\" → ouça.\n→ Valide o sentimento: \"Entendo, é desconfortável mesmo. Você fez certo em buscar avaliação.\"",
   do:"Fale o nome 2–3x. Uma pergunta de cada vez. Ouça de verdade.",
   av:"Emendar perguntas sem ouvir. Ir direto ao preço ou à agenda."},
  {n:3,title:"Só quero te entender.",t:"Intenções · 40s",tec:"Baixa a guarda",
   s:"**Setar as intenções:**\n\"{NOME}, deixa eu deixar claro: **um** — eu não vou te empurrar nada; **dois** — quero primeiro entender o seu caso pra ver o melhor caminho; **três** — e te explicar como funciona a nossa clínica, pra você decidir com clareza. Combinado?\" → **espere o \"combinado\".**",
   do:"Diga \"combinado?\" e faça silêncio até o sim.",
   av:"Emendar sem pausa — a pausa gera a concordância."},
  {n:4,title:"O que muda com a ICBARI.",t:"Pitch curto · 1 a 2 min",tec:"Vender a jornada",
   s:"**Pitch curto — venda a CONDUÇÃO (é o coração):**\n\"{NOME}, o que faz a ICBARI diferente é que a gente **conduz a sua jornada inteira**. Muita gente adia cirurgia porque se perde no meio de exames, autorizações e agendamentos. Aqui não: depois que o cirurgião avalia e indica o procedimento, **a nossa equipe marca todos os exames, as avaliações e a própria cirurgia** — e ainda te acompanha no pós-operatório. Você cuida da sua saúde, a gente cuida da logística.\"\n\n**Micropacto:** \"Faz sentido ter esse acompanhamento?\"",
   do:"Enfatize: a clínica marca tudo. Isso tira o medo do processo.",
   av:"Despejar lista de cirurgias. Aqui o foco é a CONDUÇÃO."},
  {n:5,title:"Vídeo e robótica.",t:"Segurança · 1 min",tec:"Autoridade técnica",
   s:"**Gerar segurança (sem tecniquês):**\n\"E as cirurgias são feitas por **videolaparoscopia e por técnica robótica** — que costumam ter **menos dor, recuperação mais rápida e cicatrizes menores** que a cirurgia aberta. É o que há de mais moderno para o aparelho digestivo.\"\n\nSe couber, cite **1 caso curto** de paciente que se recuperou bem.",
   do:"Traduza o benefício: menos dor, volta mais rápido à rotina.",
   av:"Prometer resultado ou falar termo técnico sem explicar."},
  {n:6,title:"As perguntas que qualificam.",t:"Qualificação · o coração do SDR",tec:"Situação + dor + urgência",
   s:"**Qualificação (anote tudo):**\n1) \"{NOME}, me conta com suas palavras: **o que você está sentindo** / qual o problema?\" → anote.\n2) \"Há **quanto tempo**? Está atrapalhando o seu dia a dia?\" → anote a urgência.\n3) \"Você já tem **algum exame ou laudo** recente? Já passou por outro médico?\" → anote.\n4) \"Você tem **convênio** ou pensa em particular?\" → anote (sem prometer cobertura).\n\n→ **Não diagnostique.** Você mapeia o caso para o cirurgião.",
   do:"Anote queixa, tempo, exames prévios e convênio — o closer/médico usa tudo.",
   av:"Dar diagnóstico ou opinião clínica. Isso é do médico."},
  {n:7,title:"O próximo passo é a consulta.",t:"Transição · 1 a 2 min",tec:"Agendar a avaliação",
   s:"**Conduzir para a consulta:**\n\"{NOME}, pelo que você me contou, o passo certo agora é uma **consulta de avaliação com o nosso cirurgião**. É nela que ele examina, esclarece suas dúvidas e, se for o caso, indica o procedimento e explica a jornada.\"\n\nFeche com **duas opções**: \"Tenho **quinta 10h ou sexta 16h** — qual encaixa melhor?\"\n\n**Se pedir preço da cirurgia:** \"O valor a gente fecha na consulta, porque depende da avaliação do médico — antes disso qualquer número seria chute, e eu não quero te enganar.\"",
   do:"Ofereça 2 horários fechados. Confirme dados de contato e e-mail.",
   av:"\"Me avisa quando puder\". Dar preço de cirurgia por telefone."},
  {n:8,title:"Objeção é pedido de clareza.",t:"Objeções · sob demanda",tec:"Devolve → reenquadra → agenda",
   s:"**Objeções — só para vender a consulta:**\n\"Está caro\" → \"A consulta é o primeiro passo e é onde tudo fica claro; sem ela nem dá pra falar de valores.\"\n\"Tenho medo de cirurgia\" → \"É super normal. A consulta serve justamente pra tirar esse medo com informação — e nossas técnicas são minimamente invasivas.\"\n\"Vou pensar\" → \"Claro. Só pra eu te ajudar: o que mais pesa na sua decisão? Enquanto isso, deixo um horário reservado.\"\n\"Preciso ver com a família\" → \"Ótimo, traga quem você quiser na consulta.\"",
   do:"Trate a objeção e volte para o agendamento. Acolha o medo.",
   av:"Discutir. Prometer cobertura de convênio. Insistir sem empatia."},
  {n:9,title:"Confirmado e sem sumiço.",t:"Fechamento do agendamento",tec:"E-mail + confirmação + lembrete",
   s:"**Fechar o agendamento:**\n\"Fechado, {NOME}: **{DIA} às {HORA}**. Vou te mandar a confirmação — **me passa seu melhor e-mail e WhatsApp**. Você vai receber lembrete um dia antes e no dia. Se precisar remarcar, é só me chamar.\"\n\nPasse o contexto quente (queixa, tempo, exames prévios, convênio) para o Closer/médico. **Nada se perde no sistema.**",
   do:"Capture e-mail/WhatsApp, confirme e ative o lembrete anti-falta.",
   av:"Encerrar sem contato e sem próximo passo."}
 ],
 "closer":[
  {n:1,title:"A decisão que reconstrói uma vida.",t:"Pré-consulta · mindset",tec:"Sereno · preparado",
   s:"**Antes da consulta:** tom sereno, ritmo calmo. Em saúde, o silêncio e a segurança valem mais que a pressa. Releia as anotações do SDR: **queixa, tempo, exames prévios, convênio (qual plano), medo**.\n\nReceba com verdade: \"Que bom te receber, {NOME}. Você **já deu o primeiro passo** ao buscar a gente, e isso costuma ser o mais difícil.\"\n\n**ESPELHAMENTO:** acompanhe o ritmo do paciente.",
   do:"Chegue calmo e preparado. O paciente sente a sua segurança.",
   av:"Chegar acelerado. Ignorar o que o SDR anotou."},
  {n:2,title:"Rapport primeiro, depois confirme o ICP.",t:"Passo 1 · 2 a 4 min",tec:"Relacionamento → confirmar o ICP",
   s:"**Primeiro a pessoa (rapport):**\n\"Olá {NOME}, tudo bem? Como você está se sentindo? <i>(ouça, acolha)</i> Que bom te receber aqui na ICBARI! Pra gente aproveitar bem essa consulta, eu vou te entender a fundo pra, junto do médico, achar o melhor caminho pro seu caso. **Pode ser?**\"\n\n**Aí sim, confirme o ICP (o {SDR} já anotou, você valida):**\n**Plano:** \"Você vai usar **convênio ou particular**? Qual é o seu **plano**?\" 🚫 (se for Hapvida: a clínica não atende, oriente com carinho e encerre)\n**Exame:** \"Você já tem **algum exame recente** (ultrassom, laudo)?\"\n**Quadro:** \"Seu **peso e altura** hoje?\" (bariátrica: **IMC ≥ 35**)\n**Decisão:** \"A **decisão é sua**? É pra **resolver agora**?\"\n\n**❌ Não é ICP:** acolha, oriente e encerre, sem conduzir a apresentação. **✅ É ICP:** recrie o pacto (\"não vim te empurrar cirurgia, vim entender e te orientar\") e siga.",
   do:"Comece pela pessoa. Só depois confirme o ICP com perguntas.",
   av:"Ir pro pitch sem rapport. Apresentar pra quem não é ICP."},
  {n:3,title:"A cirurgia é o meio. A vida de volta é o destino.",t:"Reenquadre · 1 min",tec:"O que realmente importa",
   s:"**Reenquadre o que está em jogo:**\n\"{NOME}, deixa eu te dizer uma coisa: a cirurgia é só o **meio**. O que a gente devolve pra você é a **vida de volta**: voltar a **comer sem culpa**, **dormir bem**, **largar remédios**, **brincar com quem você ama**.\n\nNão é sobre estética, é sobre **viver melhor**.\"",
   do:"Fale devagar. Deixe a frase respirar.",
   av:"Falar de técnica ou preço aqui. É momento de sentido."},
  {n:4,title:"Não é sobre estética. É sobre viver.",t:"A dor · 1 a 2 min",tec:"Espelhar o que a obesidade cobra",
   s:"**Mostre, com empatia, o que isso cobra (use o que ELE te disse):**\n**Cansaço no dia a dia:** \"Subir uma escada, brincar com quem você ama, trabalhar sem dor, a rotina vai ficando pesada, né?\"\n**A saúde em risco:** \"Pressão, diabetes, apneia. Cada mês cobra um pouco mais do corpo.\"\n**A autoestima:** \"Você merece se olhar no espelho e gostar do que vê. Isso também é saúde.\"",
   do:"Conecte cada ponto ao que ele já contou. Valide o sentimento.",
   av:"Dramatizar ou culpar. Fazer a pessoa se sentir mal."},
  {n:5,title:"Há quanto tempo você convive com isso?",t:"Pergunta · silêncio",tec:"Deixe o paciente refletir",
   s:"**Pergunte e fique em silêncio:**\n\"{NOME}, uma pergunta sincera: **há quanto tempo você convive com isso**, sem resolver de verdade?\"\n\n→ **Cale-se.** Deixe ele pensar e responder. Não tem resposta certa.",
   do:"Faça a pergunta e espere. O silêncio trabalha por você.",
   av:"Responder no lugar dele. Preencher o silêncio."},
  {n:6,title:"O que você já deixou de fazer por causa disso?",t:"Pergunta · silêncio",tec:"Trazer a perda à tona",
   s:"\"E **o que você já deixou de fazer** por causa disso? De fazer, de viver, de vestir. O que ficou pra trás?\"\n\n→ **silêncio.** Deixe ele completar.",
   do:"Uma pergunta de cada vez. Ouça de verdade.",
   av:"Emendar perguntas sem ouvir a anterior."},
  {n:7,title:"Quanto isso já te custou?",t:"Pergunta · implicação",tec:"O custo de adiar",
   s:"\"E a última: **quanto isso já te custou**? Em saúde, em autoestima, em momentos. O que você perdeu por adiar?\"\n\n→ deixe a resposta ecoar. É aqui que a decisão amadurece.",
   do:"Deixe ele mesmo dimensionar o custo de não agir.",
   av:"Apressar. Partir pro pitch antes de ele responder."},
  {n:8,title:"Aqui você tem um time inteiro cuidando de você.",t:"O método · 1 a 2 min",tec:"Multidisciplinar · segurança",
   s:"**Apresente o cuidado (não a cirurgia):**\n**Multidisciplinar:** \"Nutricionista, psicóloga e endocrinologista junto do cirurgião. Você **não decide sozinho**.\"\n**Precisão:** \"Vídeo e robótica: **menos dor**, cicatrizes menores e recuperação mais rápida.\"\n**Segurança:** \"Protocolos rigorosos, monitoramento do começo ao fim.\"\n**Massa magra:** \"Não é só perder peso: é **ganhar saúde e manter** o resultado.\"",
   do:"Venda o time e a segurança. Traduza sem tecniquês.",
   av:"Listar tudo correndo. Usar jargão médico."},
  {n:9,title:"Faz diferença ter um time inteiro do seu lado?",t:"Micropacto",tec:"Confirmar valor percebido",
   s:"\"{NOME}, **faz diferença** ter um time inteiro do seu lado? Porque aqui você **nunca caminha sozinho**, cada etapa é acompanhada, do preparo ao pós.\"\n\n→ pegue o **sim** antes de avançar.",
   do:"Colha a concordância. É um micropacto.",
   av:"Seguir sem confirmar. Responder por ele."},
  {n:10,title:"Cada passo cuidado, do preparo ao pós.",t:"A jornada · 1 min",tec:"Mostrar o caminho",
   s:"**Mostre a jornada, passo a passo:**\n\"O caminho é este: a gente marca seus **exames pré-operatórios** e as **avaliações** (cardiologista, anestesista e o que o seu caso pedir), depois o **retorno ao médico** com os resultados, aí **marcamos a cirurgia** no hospital e cuidamos do **pós**.\"\n\n**Micropacto:** \"Ficou claro o caminho?\"",
   do:"Deixe visual e simples. Um passo leva ao outro.",
   av:"Complicar. Passar rápido sem confirmar."},
  {n:11,title:"Dois cirurgiões cuidando de você.",t:"Quem vai te operar · 1 min",tec:"Autoridade dos médicos",
   s:"\"Você vai ser operado por quem faz disso a vida inteira:\n**Dr. Wander Carvalho**, sócio-fundador, vídeo e robótica, foco em massa magra e acompanhamento a longo prazo.\n**Dr. Pedro Pinheiro**, sócio-fundador, vídeo e robótica, cuidado integral antes e depois.\"\n\nReforce: **200+ vidas transformadas** e **120+ avaliações 5 estrelas**.",
   do:"Passe segurança pelos nomes e pela experiência.",
   av:"Inventar números. Prometer resultado."},
  {n:12,title:"Hospital de referência, equipe completa.",t:"Onde acontece · 40s",tec:"Segurança da estrutura",
   s:"\"A sua cirurgia é feita em **hospital acreditado**, com **anestesista dedicado** e monitoramento contínuo, como o **DF Star** e o **Santa Helena**. Seja por convênio ou particular, a gente te orienta em cada passo.\"",
   do:"Mostre solidez sem prometer cobertura de convênio.",
   av:"Prometer que o convênio cobre. Garantir um hospital específico."},
  {n:13,title:"A clínica marca todos os seus exames.",t:"A condução · 1 min",tec:"Você não corre atrás de nada",
   s:"**Este é o grande diferencial, venda com orgulho:**\n\"Todos os exames e avaliações entram no seu plano e **a clínica agenda cada um**, com aviso no **WhatsApp e no e-mail**. Você só precisa **comparecer**. Todo o resto é com a gente.\"\n\nMostre o checklist: consulta ✓, avaliações, exames, anestesista e a cirurgia, tudo marcado pela clínica.",
   do:"Enfatize a condução completa. É o que tira o medo de se perder.",
   av:"Minimizar esse diferencial. Ele é o coração da ICBARI."},
  {n:14,title:"Não é só a cirurgia. É o cuidado completo.",t:"O que está incluído · 1 min",tec:"Ancorar valor antes do preço",
   s:"**Liste o que está incluído (ancora o valor):**\n• **Avaliação pré-cirúrgica completa** (exames, psicóloga e nutri).\n• **Cirurgia em hospital acreditado**, com anestesista dedicado.\n• **Vídeo e robótica**: menos dor, volta às atividades leves em cerca de 2 semanas.\n• **Nutricionista por 6 meses**: perda consistente, sem rebote.\n• **Suporte psicológico incluso**: sustenta o resultado.\n\n\"É um **cuidado completo**, não só o ato cirúrgico.\"",
   do:"Some tudo que está incluído ANTES de falar de preço.",
   av:"Pular pro preço sem ancorar o valor do pacote."},
  {n:15,title:"Gente de verdade que mudou de vida.",t:"Prova · 30s",tec:"Histórico, não promessa",
   s:"\"E não é promessa, é **histórico**: **200+ vidas transformadas**, **120+ avaliações 5 estrelas** e **6 meses** de acompanhamento incluso.\"",
   do:"Números reais, ditos com firmeza.",
   av:"Exagerar. Inventar."},
  {n:16,title:"Gente de verdade, avaliando de verdade.",t:"Prova social · 1 min",tec:"Depoimentos reais do Google",
   s:"**Mostre 1 ou 2 depoimentos reais (Google):**\n\"Fiz bariátrica com o Dr. Wander. A melhor decisão que tomei em 2025.\" — Sarah Moura\n\"Retirada da vesícula. Me senti segura, sem pressa e sem medo.\" — Pollyana Rosa\n\nSão **avaliações reais no Google**, mais de 120 com 5 estrelas.",
   do:"Escolha o depoimento do MESMO procedimento do paciente.",
   av:"Ler todos. Inventar depoimento."},
  {n:17,title:"O antes e o depois de quem passou por aqui.",t:"Prova · 30s",tec:"Antes e depois",
   s:"**Mostre um antes e depois** de um paciente do **mesmo procedimento**, quando houver.\n\"Isso aqui foi uma pessoa como você, que decidiu começar. Hoje está do outro lado.\"",
   do:"Use caso do mesmo procedimento. Respeite a privacidade.",
   av:"Mostrar caso que não tem a ver com o dele."},
  {n:18,title:"Você se imagina com 10, 20, 30 quilos a menos?",t:"Projeção · silêncio",tec:"Benefício do benefício",
   s:"**Projete o depois:**\n\"{NOME}, fecha os olhos por um segundo. **Você se imagina com 10, 20, 30 quilos a menos?** Se vê assim?\"\n\n→ **silêncio.** Deixe ele se ver lá.",
   do:"Faça a pergunta e cale-se. Deixe a imagem se formar.",
   av:"Responder por ele. Voltar ao racional cedo."},
  {n:19,title:"Como seria um dia comum seu, sem esse peso?",t:"Projeção · silêncio",tec:"Futuro concreto",
   s:"\"E **como seria um dia comum seu, sem esse peso**? Do acordar ao dormir. Como seria?\"\n\n→ deixe ele descrever. Emoção fecha, razão só justifica.",
   do:"Deixe ele detalhar o próprio futuro.",
   av:"Apressar. Cortar a fala."},
  {n:20,title:"O que você faria de novo, que hoje deixa de fazer?",t:"Projeção · silêncio",tec:"Reacender o desejo",
   s:"\"E a última: **o que você faria de novo**, que hoje deixa de fazer? Aquilo que você adia porque hoje não consegue?\"\n\n→ deixe a resposta ecoar. Ela é o motivo dele.",
   do:"Guarde o que ele responder. É a âncora do fechamento.",
   av:"Ignorar a resposta. Não usar depois."},
  {n:21,title:"Vamos começar?",t:"Oferta e fechamento · 5 a 10 min",tec:"Valor → preço → objeções → começar",
   s:"**Antes do preço, o valor:**\n\"Nesse acompanhamento está **tudo**: a condução da jornada, a marcação dos exames e da cirurgia, a técnica moderna e o pós. É um **cuidado completo**.\"\n\n**Apresente o valor com firmeza e faça silêncio.** Se houver convênio: explique o que a clínica ajuda a solicitar, **sem prometer cobertura** (\"quem autoriza é o convênio, a gente prepara toda a documentação\").\n\n**Isolar o preço:** \"Se o investimento couber no seu planejamento, é isso que você quer resolver, certo?\"\n\n**Facilidades:** parcelamento em até **12x** e apoio com o convênio. Acompanhamento no pós em **1, 2 e 3 meses**.\n\n**Objeções (acolhe → reenquadra → encaminha):**\n\"Vou pensar\" → \"Faz sentido. Sua dúvida é sobre o **procedimento**, o **valor** ou o **momento**?\"\n\"Medo da cirurgia\" → \"É natural. Por isso a gente conduz passo a passo, com técnica minimamente invasiva. O que mais te assusta?\"\n\"Preciso ver o convênio\" → \"Perfeito, já deixo a documentação pronta. Enquanto isso, começamos os exames?\"\n\n**Encaminhar:** \"O primeiro passo concreto é **começar os exames**. Posso já iniciar sua jornada no sistema e a equipe marca o primeiro exame ainda essa semana?\"",
   do:"Ancore o valor, isole o preço e faça silêncio. Feche pelo próximo passo (iniciar exames).",
   av:"Jogar o preço sem ancorar. Prometer convênio. Desistir na primeira objeção."},
  {n:22,title:"Bem-vindo à sua nova vida.",t:"Pós-fechamento",tec:"Iniciar a jornada · handoff CS",
   s:"**Comemore e inicie de verdade:**\n\"{NOME}, **parabéns pela decisão!** A gente transforma vidas **com você**, não **por você**. Vamos começar!\"\n\nAbra a **Jornada do Paciente** no sistema (escolhendo o procedimento, os exames entram automaticamente) e passe o caso pro **CS/pós-venda**. \"Você vai receber tudo no **WhatsApp e no e-mail**.\"",
   do:"Crie a jornada na hora e faça o handoff pro CS. Comemore com o paciente.",
   av:"Encerrar frio. Deixar a jornada sem começar."}
 ],
 "jornada":[
  {n:1,title:"Boas-vindas",t:"CS · Dia 0",tec:"Acolher + alinhar",
   s:"Dê as **boas-vindas**, confirme dados e e-mail e explique: **a clínica vai marcar todos os exames e a cirurgia**. Envie a **lista de exames** do procedimento (ela já aparece na jornada).",
   do:"Confirme WhatsApp e e-mail. Envie a lista de exames.",
   av:"Sumir depois do fechamento."},
  {n:2,title:"Marcação dos exames",t:"CS · Exames",tec:"Agendar + avisar",
   s:"Para cada exame/avaliação: **agende** (médico/local, telefone, data), gere o **evento no calendário** do paciente e envie por **WhatsApp e e-mail**. Registre a **data prevista do resultado**.",
   do:"Um item de cada vez. Sempre envie calendário + WhatsApp + e-mail.",
   av:"Marcar sem avisar o paciente."},
  {n:3,title:"Resultados e retorno",t:"CS · Resultados → Retorno",tec:"Coletar + retornar",
   s:"Acompanhe os **resultados** (ligue para confirmar as datas). Com tudo em mãos, **marque o retorno ao cirurgião** para a decisão da cirurgia.",
   do:"Só marque o retorno com todos os resultados prontos.",
   av:"Marcar retorno faltando exame."},
  {n:4,title:"Marcar a cirurgia",t:"CS · Hospital",tec:"Checklist do hospital",
   s:"Marque a cirurgia no hospital e confira o **checklist**: pedido médico com código, laudos dos exames, termos de consentimento (cirúrgico e anestésico), autorização do convênio/OPME quando houver e documentos do paciente.",
   do:"Use o checklist da jornada. Confirme autorização antes da data.",
   av:"Marcar a data sem a autorização/documentos."},
  {n:5,title:"Pós-operatório",t:"CS · 1, 2 e 3 meses",tec:"Cuidar que continua",
   s:"Faça o acompanhamento em **1, 2 e 3 meses**, **independentemente** de o paciente ter retornado. Pergunte como está, registre a observação e ofereça ajuda. É aqui que nasce a **indicação**.",
   do:"Contate nos 3 marcos. Registre tudo (nada se perde).",
   av:"Só acompanhar quem reclama."}
 ]
};

/* ===== Roteiro do SDR POR ORIGEM do lead (anúncio/tráfego · indicação · retorno/frio) =====
   Espelha o Script de Vendas: o que a pessoa vai FALAR, palavra por palavra, sabendo o que fazer. */
window.ROTEIRO_ICB_SDR=function(orig){
 orig=orig||"anuncio";
 var s1={title:"Antes de discar",t:"Pré-ligação · 30s",tec:"Preparação · espelhamento",
  s:"**Respire, sorria, tom firme e acolhedor.** Você não está vendendo, está cuidando de uma pessoa que procurou ajuda para um problema de saúde.\nTenha à mão: **nome**, **por qual canal** a pessoa chegou e a **queixa/procedimento** de interesse.\n\n**ESPELHAMENTO (regra de ouro):** copie o ritmo da pessoa. Fala rápido, fale rápido; fala devagar, vá devagar.",
  do:"Sorria (ouve-se no telefone). Uma pergunta de cada vez, ouça de verdade.",
  av:"Ligar no automático, sem energia. Ir direto ao procedimento ou ao preço."};
 var openings={
  anuncio:{title:"Abra e prenda em 10 segundos",t:"Abertura · veio de anúncio",tec:"Rapport · referência ao anúncio",
   s:"\"Olá **{NOME}**, tudo bem? Aqui é **{SDR}**, da ICBARI. Vi que você buscou informação sobre **{PROCEDIMENTO}**. Posso te fazer umas perguntas rápidas pra entender seu caso e te orientar do jeito certo?\"",
   do:"Fale devagar, use o nome, peça permissão pra perguntar.",
   av:"Despejar informação. Falar de preço ou de cirurgia agora."},
  indicacao:{title:"Use a confiança da indicação",t:"Abertura · veio por indicação",tec:"Rapport · quem indicou",
   s:"\"Olá **{NOME}**, tudo bem? Aqui é **{SDR}**, da ICBARI. Quem me passou seu contato falou que você está querendo resolver **{QUEIXA}**. Que bom que chegou até a gente! Deixa eu te entender melhor pra já te direcionar.\"",
   do:"Use a confiança de quem indicou. Agradeça e acolha.",
   av:"Ignorar a indicação. Tratar como lead frio qualquer."},
  retorno:{title:"Reabra com carinho, sem cobrar",t:"Abertura · já falou com a gente antes",tec:"Reconexão sem cobrança",
   s:"\"Oi **{NOME}**, aqui é **{SDR}**, da ICBARI. Você chegou a falar com a gente sobre **{PROCEDIMENTO}** um tempo atrás. Tô te ligando com carinho só pra saber **como você está com isso hoje**. Tem um minutinho?\"",
   do:"Tom leve e acolhedor. Zero cobrança pelo sumiço.",
   av:"Cobrar (\"você sumiu\"). Recomeçar o pitch do zero."}
 };
 var s3anuncio={title:"Descubra o que a pessoa sente",t:"Acolhimento · 1 a 2 min",tec:"Escuta · dor",
  s:"**Acolha e ouça de verdade (sem diagnosticar):**\n\"Me conta com suas palavras: **o que você está sentindo** / o que quer resolver?\" → ouça.\n\"Há **quanto tempo** você convive com isso? Está atrapalhando o seu dia a dia?\" → ouça e valide: \"Entendo, é desconfortável mesmo. Você fez certo em buscar avaliação.\"",
  do:"Ouça mais do que fala. Valide o sentimento antes de seguir.",
  av:"Diagnosticar. Interromper. Emendar perguntas sem ouvir."};
 var s3retorno={title:"Descubra o que a pessoa sente",t:"Reabertura · achar o que travou",tec:"Sem culpa · dor",
  s:"**Reabra sem culpa e descubra o que travou:**\n\"Só pra eu te entender e te ajudar melhor agora: **o que fez você segurar** naquele momento? Foi o **tempo**, o **valor**, algum **medo**, ou a dúvida com o **convênio**?\" → ouça sem julgar.\n\"E hoje, o **{QUEIXA}** ainda te incomoda? Em quê ele atrapalha o seu dia?\"",
  do:"Descubra a objeção real de antes. Acolha sem cobrar.",
  av:"Julgar o motivo. Insistir antes de entender."};
 var s4={title:"Mostre o custo de adiar, sem pressão",t:"Clareza e urgência · 1 a 2 min",tec:"SPIN clínico",
  s:"**Reaja ao que ele disse, com empatia (SPIN clínico):**\n**Situação:** \"Entendi. E no dia a dia, isso te limita em quê: trabalho, sono, alimentação?\"\n**Problema:** \"O que mais te incomoda nisso hoje?\"\n**Implicação:** \"E deixar como está, sem avaliar, o que pode acontecer? Costuma melhorar sozinho, esperando?\"\n**Necessidade:** \"Se um cirurgião avaliasse e a clínica cuidasse de todos os exames pra você, isso te ajudaria?\"",
  do:"Faça a pessoa perceber sozinha o custo de adiar. Pergunte, não afirme.",
  av:"Assustar, dramatizar ou empurrar. Diagnosticar."};
 var s5={title:"As últimas perguntas, para anotar no CRM",t:"Qualificação · o coração do SDR",tec:"ICP · registro",
  s:"**As perguntas que definem o perfil (anote tudo):**\n\"Você já tem **algum exame ou laudo** recente? Já passou por outro médico?\"\n\"Você já tem **indicação de cirurgia** ou quer uma **avaliação**?\"\n\"Vai ser por **convênio** ou **particular**?\" (se convênio: **qual plano?** 🚫 se for Hapvida, a clínica não atende: oriente com carinho e encerre)\n\"Você é de **Brasília e entorno**?\"",
  do:"Anote cada resposta no CRM. Elas definem o perfil e preparam o Closer.",
  av:"Prometer cobertura de convênio. Diagnosticar. Pular o registro."};
 var s6={title:"Fale de quem vai cuidar da pessoa",t:"Segurança · 1 min",tec:"Autoridade · condução",
  s:"**Gere segurança e venda a condução (sem tecniquês):**\n\"{NOME}, o que faz a ICBARI diferente é que a gente **conduz a sua jornada inteira**. Depois que o cirurgião avalia e indica, **a nossa equipe marca todos os exames, as avaliações e a própria cirurgia**, e ainda te acompanha no pós.\"\n\"As cirurgias são feitas por **videolaparoscopia e por técnica robótica**, que costumam ter **menos dor, recuperação mais rápida e cicatrizes menores**.\"\nSe couber, cite **1 caso curto** de paciente que se recuperou bem.",
  do:"Venda o cuidado e a equipe, não a cirurgia. Prova social curta ajuda.",
  av:"Tecniquês. Promessa de resultado. Falar demais."};
 var s7={title:"Ofereça o próximo passo",t:"Transição · o objetivo do SDR",tec:"Agendar a avaliação",
  s:"**Conduza para a consulta:**\n\"{NOME}, pelo que você me contou, o passo certo agora é uma **consulta de avaliação com o nosso cirurgião**. É nela que ele te examina, tira suas dúvidas e, se for o caso, indica o procedimento e explica a jornada. E aqui **a clínica marca todos os exames e a cirurgia pra você**.\"\nFeche com **duas opções**: \"Tenho **amanhã 10h ou sexta 16h**, qual encaixa melhor?\"\n\n**Se pedir preço da cirurgia:** \"O valor a gente fecha na consulta, porque depende da avaliação do médico. Antes disso qualquer número seria chute, e eu não quero te enganar.\"",
  do:"Ofereça 2 horários fechados. Reforce que a clínica marca tudo.",
  av:"\"Me avisa quando puder.\" Dar preço de cirurgia por telefone."};
 var s8={title:"Objeções comuns, respostas prontas",t:"Objeções · sob demanda",tec:"Acolhe → reenquadra → agenda",
  s:"**Sempre para vender a consulta (não a cirurgia):**\n\"Está caro\" → \"A consulta é o primeiro passo e é onde tudo fica claro; sem ela nem dá pra falar de valores.\"\n\"Tenho medo de cirurgia\" → \"É super normal. A consulta serve justamente pra tirar esse medo com informação, e nossas técnicas são minimamente invasivas.\"\n\"Vou pensar\" → \"Claro. Só pra eu te ajudar: o que mais pesa na sua decisão? Enquanto isso, deixo um horário reservado.\"\n\"Preciso ver com a família\" → \"Ótimo, traga quem você quiser na consulta.\"",
  do:"Acolha, reenquadre e volte pro agendamento.",
  av:"Discutir. Desistir na primeira objeção."};
 var s9={title:"Feche o combinado e evite a falta",t:"Fechamento do agendamento",tec:"WhatsApp na hora · anti no-show",
  s:"\"Fechado, **{NOME}**: **{DIA} às {HORA}** 🙌. Vou te mandar a confirmação aqui, me passa seu **melhor e-mail e WhatsApp**. Você recebe lembrete um dia antes e no dia. Se tiver exames antigos, leve com você. Qualquer coisa é só me chamar.\"",
  do:"Capture e-mail e WhatsApp. Ative o lembrete. Blinde a falta.",
  av:"Encerrar sem contato e sem confirmação."};
 var s10={title:"Você não vende cirurgia. Você abre a porta.",t:"Handoff · propósito",tec:"Contexto quente pro Closer",
  s:"**Passe o bastão e feche com propósito:**\nPasse todo o contexto quente pro Closer/médico: **queixa, tempo, exames prévios, convênio (qual plano) e perfil**. **Nada se perde no sistema.**\n\n\"Já deixei tudo certinho aqui, **{NOME}**. Te espero no dia, vai dar tudo certo 💚\"\n\nLembre-se: você não vendeu uma cirurgia. Você **abriu a porta** pra alguém cuidar da própria saúde.",
  do:"Handoff completo pro Closer. Registre tudo.",
  av:"Deixar o Closer no escuro. Esquecer de registrar."};
 var s3=(orig==="retorno")?s3retorno:s3anuncio;
 var arr=[s1,(openings[orig]||openings.anuncio),s3,s4,s5,s6,s7,s8,s9,s10].map(function(x){return Object.assign({},x);});
 arr.forEach(function(x,i){x.n=i+1;});
 return arr;
};
/* default (compatibilidade): a aba SDR do roteiro começa no fluxo de anúncio */
window.ROTEIRO_ICBARI.sdr=window.ROTEIRO_ICB_SDR("anuncio");
